# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 00:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modules.Songs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Albums', '0001_initial'),
        ('Artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('publication_date', models.DateField(null=True)),
                ('cover', models.URLField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('category', models.CharField(choices=[('MET', 'Metal'), ('COU', 'Country'), ('ROC', 'Rock'), ('FOL', 'Folklore'), ('ALT', 'Alternative'), ('RNB', 'R&B-Soul'), ('ELE', 'Electronic'), ('POP', 'Pop'), ('LAT', 'Latin'), ('ClA', 'Classical')], max_length=100)),
                ('song_file', models.FileField(upload_to=modules.Songs.models.song_directory_path)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_song', to='Albums.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_song', to='Artists.Artist')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_comments', to='Songs.Song'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
